openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /state:
    get:
      description: Stav využitých zdrojů všech kontejnerů uživatele vůči přiděleným zdrojům uživatele. V případě, že uživatel klikne na frontendu na možnost statistiky, tak se API volá každou vteřinu
      responses:
        '200':
          description: objekt stavu
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    $ref: '#/components/schemas/ResourceState'
                  
  /stateDetailed:
    get:
      responses:
        '200':
          description: Pole objektů stavů se jmény a ID kontejnerů
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name: 
                      type: string
                    state: 
                      $ref: '#/components/schemas/ResourceState'
  /instances:
    get:
      responses:
        '200':
          description: OK
  /instances/create:
    get:
      responses:
        '200':
          description: Successful image list return
          content:
            application/json:
              schema:
                type: object
                properties:
                  configurationTypes:
                    type: array
                    items:
                      type: string
                      description: Distro name
                  applicationsToInstall:
                    type: array
                    items:
                      type: string
                      description: Application name
    post:
      description:
        fdasfsd
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                autostart:
                  type: boolean
                persistent:
                  type: boolean
                configurationType:
                  type: string
                applicationToInstall:
                  type: array
                  items:
                    description: Application name
                    type: string
                enableGUIAccess:
                  type: boolean
              required:
                - name
                - autostart
                - persistent
                - configurationType
                - applicationToInstall
      responses:
        '201':
          description: Created
        '403':
          description: Forbidden # creation of container failed, not enough resources or something else went wrong TODO: further specification
  /instances/{id}/state:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  /instances/{id}/console:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  #/instances/{id}/files:
  #  get:
  #    parameters:
  #      - in: path
  #        required: true
  #        name: id
  #        schema:
  #          type: integer
  #        description: Id kontejneru, ke kterému vztahujeme naši operaci
  #    responses:
  #      '200':
  #        description: OK
  /instances/{id}/snapshots:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  /instances/{id}/snapshots/{snapshotId}:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
        - in: path
          required: true
          name: snapshotId
          schema:
            type: integer
          description: Id snapshotu, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  /instances/{id}/backups/{backupId}/export:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
        - in: path
          required: true
          name: backupId
          schema:
            type: integer
          description: Id snapshotu, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
components:
  schemas:
    ResourceState:
      type: object
      properties:
        CPU:
          type: object
          properties:
            consumedTime:
              type: integer
              description: Čas práce procesoru v sekundách
            percentConsumed:
              type: integer
              description: Procento přidělené kapacity procesoru využité všemi kontejnery dohromady
        RAM:
          type: object
          properties:
            currentlyConsumedMemory:
              type: integer
              description: Využití paměti RAM v KB
            percentConsumed:
              type: integer
              description: Procento přidělené kapacity RAM využité všemi kontejnery dohromady
        drive:
          type: object
          properties:
            currentlyConsumedMemory:
              type: integer
              description: Využití paměti disku v KB
            percentConsumed:
              type: integer
              description: Procento přidělené kapacity RAM využité všemi kontejnery dohromady
        network:
          type: object
          properties:
            uploadInKB:
              type: integer
              description: Využití uploadu v KB
            downloadKB:
              type: integer
              description: Využití downloadu v KB
        numberOfProcesses:
          type: integer
          description: Počet procesů