openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /state:
    get:
      summary: statistika využitých zdrojů všech kontejnerů uživatele vůči přiděleným zdrojům uživatele
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  CPU:
                    type: object
                    properties:
                      consumedTime:
                        type: integer
                        description: Čas práce procesoru za posledních deset sekund
                      percentConsumed:
                        type: integer
                        description: Procento přidělené kapacity procesoru využité všemi kontejnery dohromady
                  username:
                    type: string
                    description: The user name.


  /stateDetailed:
    get:
      responses:
        '200':
          description: OK
  /instances:
    get:
      responses:
        '200':
          description: OK
  /instances/{id}/console:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  /instances/{id}/files:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  /instances/{id}/snapshots:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  /instances/{id}/snapshots/{snapshotId}:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
        - in: path
          required: true
          name: snapshotId
          schema:
            type: integer
          description: Id snapshotu, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
  /instances/{id}/backups/{backupId}/export:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
          description: Id kontejneru, ke kterému vztahujeme naši operaci
        - in: path
          required: true
          name: backupId
          schema:
            type: integer
          description: Id snapshotu, ke kterému vztahujeme naši operaci
      responses:
        '200':
          description: OK
